package summ.nlp.preprocesing;

public enum PreProcessingTypes {
	SENTENCE_SEGMENTATION, 
	REMOVE_PUNCTUATION, 
	TO_LOWER_CASE, 
	SIMPLE_TOKENIZATION,
	WHITE_SPACE_TOKENIZATION,
	NEURAL_TOKENIZATION,
	REMOVE_STOPWORDS,
	NER,
	POS,
	IDENTIFY_TITLES,
	LEMMATIZATION
}
